import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    padding: 24,
    paddingHorizontal: 24,
    paddingTop: 80,
    paddingBottom: 24,
  },
  header: {
    marginBottom: 32,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 8,
    paddingBottom: 7,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 16,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  label: {
    color: colors.textSecondary,
    marginBottom: 8,
    marginTop: 10,
    fontSize: 16,
  },
  currencyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  swapButton: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 24,
  },
  swapButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontSize: 20,
    fontWeight: "600",
  },
  convertButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    marginTop: 16,
  },
  convertButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
  },
  viewResultButton: {
    backgroundColor: colors.secondary,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    marginTop: 12,
  },
  viewResultButtonText: {
    color: "#0f172a",
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
  },
  convertButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  cardResult: {
    backgroundColor: colors.cardBackground,
    borderRadius: 24,
    padding: 24,
    marginTop: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
  },
  cardResultError: {
    color: colors.secondary,
    fontSize: 16,
    fontWeight: "700",
  },
  cardResultTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  cardResultValue: {
    color: colors.text,
    fontSize: 34,
    fontWeight: "900",
    marginBottom: 12,
  },
  cardResultInfo: {
    borderTopWidth: 1,
    borderTopColor: colors.disabled,
    paddingTop: 12,
  },
  cardResultText: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  cardResultFooter: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: 14,
  },
  textInput: {
    backgroundColor: "transparent",
    color: colors.text,
    fontSize: 24,
    fontWeight: "700",
    padding: 16,
    borderRadius: 8,
  },
  inputBox: {
    borderRadius: 24,
    backgroundColor: colors.inputBackground,
    padding: 18,
    marginBottom: 16,
  },
  inputRow: {
    position: "relative",
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    overflow: "hidden",
  },
  inputSymbol: {
    color: colors.textSecondary,
    fontSize: 18,
    marginRight: 8,
  },
  inputSymbolLeft: {
    position: "absolute",
    left: 16,
    top: 18,
    color: colors.destaque,
    fontSize: 18,
  },
  inputSymbolLeftContainer: {
    position: "absolute",
    left: 12,
    top: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  inputSymbolLeftItem: {
    color: colors.destaque,
    fontSize: 18,
    marginRight: 6,
  },
  inputSymbolOverlay: {
    position: "absolute",
    right: 16,
    top: 18,
    color: colors.destaque,
    fontSize: 18,
  },
  inputTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  inputTopLeft: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  inputTopRight: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  inputBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  inputBottomLeft: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  inputBottomRight: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  inpoutCounteiner: {
    fontSize: 12,
  },
});
